### ISSUE TITLE
Add a proper "save annotation" button.

### ISSUE THREAD

**Issue by DavidStirling** [piximi/image-viewer#130]
Needing to use the "enter" key to accept an annotation is not intuitive or even documented on the page. The shortcut is useful, but I think there should be a proper button somewhere.

**Comment by alicelucas** [comment]
@DavidStirling Thanks for suggesting this!
We were just discussing this and thought that maybe it would be even better to not ask the user to confirm an annotation. On mouse up, the annotation would be automatically confirmed. The user could always go back to it and delete or change it if needed.
What do you think ? Our thought process here is to make the experience faster with less steps in between so that the user can go through these annotations as quickly as possible.

**Comment by DavidStirling** [comment]
@alicelucas - I think that automatically confirming will make things tricky when using the 'add' tool and similar modification modes. What happens if the new annotation box touches 2 objects?

I think an alternative might be to have it so that clicking a category saves a region - so you'd draw the object, then click which category you drew to lock that object. You could even do a small popup next to the bounding box to quickly pick a category.

**Comment by alicelucas** [comment]
@DavidStirling Good point! We actually did have this pop-up idea (#134). Currently we are saying that this pop-up should appear only if "Unknown" is the selected category, but I think you are saying that that pop-up would appear on each mouse up. The pop-up would list the available categories and would also offer the possibility of creating a new one. Clicking on one of the options would confirm the annotation.

@0x00b1 and I will be doing more thinking about this. We're hoping that we can get more input from the group on Friday.

**Comment by alicelucas** [comment]
We have the functionality so I'm closing this issue. We still need to style the button, and would be nice to have a "pointer" type of cursor when hovered above the button.
