### ISSUE TITLE
Enhancement: image should resize to fill available browser size

### ISSUE THREAD

**Issue by pearlryder** [piximi/image-viewer#140]
See all the gray to either side of the image? I want to stretch it to fit as much of my window as possible, to make annotation easier. 

![Screen Shot 2021-03-24 at 4 07 35 PM](https://user-images.githubusercontent.com/28375904/112376977-8c90b980-8cbb-11eb-8f6c-d3226da4f2f2.png)

**Comment by alicelucas** [comment]
@pearlryder re this: we have increased the Stage (the container that contains the image) to twice what it used to be (1000 x 1000) so that the image takes much more space than before. 
We don't know yet if we want to allow the user to resize the image. Currently the user does have the option to zoom in and out of the image. Do you think that the ability to resize the image is a must-have feature ?

**Comment by 0x00b1** [comment]
I agree with @pearlryder

**Comment by pearlryder** [comment]
I just checked your new stage on my external monitor and the same problem happens -- it's pretty easy to stretch the window out so that the stage is larger than the image. Sometimes we'll be annotating small details, so being able to get the image really big would be great in the future. Prioritize as you see fit!

**Comment by 0x00b1** [comment]
`canvas` now fills the container when sufficiently zoomed, e.g.

![Uploading image.png…]()
