### ISSUE TITLE
Color Selection broken on zoomed in image

### ISSUE THREAD

**Issue by pearlryder** [piximi/image-viewer#142]
I suspect that this relates an underlying zoom issues raised by @alicelucas in https://github.com/piximi/image-viewer/issues/136

Color selection on a zoomed in example image appears to be selecting colors on the wrong zoom level (the selection is much bigger than the objects in my image and it doesn't correspond to the shapes I'm selecting). 

Please watch video for demo:

https://user-images.githubusercontent.com/28375904/112380813-383c0880-8cc0-11eb-8452-55441d3050f4.mov

**Comment by alicelucas** [comment]
Thanks @pearlryder for this!
This video shows two different problems:
(1) Zooming in to the wrong region. This is fixed with a recent commit so I am going to close this issue.
(2) The color map not updating to the right new scale (or something of the sorts). I am going to create a separate issue for that.
