### ISSUE TITLE
Modify exposure, brightness, contrast, and black point

### ISSUE THREAD

**Issue by 0x00b1** [piximi/image-viewer#76]

**Comment by pearlryder** [comment]
Just ran into needing this when I tried to upload a 16-bit tiff for annotation. The image loaded as completely black, which may either be due to a brightness / contrast issue or the data isn't being imported properly.


<img width="1370" alt="Screen Shot 2021-03-22 at 5 26 39 PM" src="https://user-images.githubusercontent.com/28375904/112060660-d9e21f00-8b33-11eb-85c0-baee9b674532.png">
