### ISSUE TITLE
Object annotation tool creates rectangles instead of paths

### ISSUE THREAD

**Issue by DavidStirling** [piximi/image-viewer#89]
For some reason hitting 'enter' to save an objectselection region just fills the entire box instead of the previewed, detected shape.

![objectselection2](https://user-images.githubusercontent.com/26802537/111530570-d4529680-8739-11eb-8ef6-569822ff1833.png)

**Comment by 0x00b1** [comment]
Confirmed! 

I believe there is an issue where the object annotation tool believes it's the rectangular annotation tool.

**Comment by alicelucas** [comment]
This is fixed so I'm going to close. 

I'll note that I observed an unrelated problem to this issue that @0x00b1 will know how to approach better than I do: 
Because the `this.annotating` of the `ObjectSelection` is set to `true` in an async manner, it doesn't actually get reflected in `Stage` unless we force the re-rendering. Currently the results are shown only if the user did a mouse movement (which triggers the `update` hook that we have in there).

We need to force re-render when the async call has completed, but it's not clear to me where/how we should do it.
